const imgPrefixMSMS = "/building_photos_archive/bhs/";
const imgListBHS = [
  "1.jpg",
  "IMG_0108.jpg",
  "IMG_0227.jpg",
  "IMG_0229.jpg",
  "IMG_0248.jpg",
  "IMG_0249.jpg",
  "IMG_0253.jpg",
  "IMG_0268.jpg",
  "IMG_0277.jpg",
  "IMG_0291.jpg",
  "IMG_0327.jpg",
  "IMG_0336.jpg",
  "IMG_0337.jpg",
  "IMG_0338.jpg",
  "IMG_0388.jpg",
  "IMG_0428.jpg",
  "IMG_0464.jpg",
  "IMG_0505.jpg",
  "IMG_0506.jpg",
  "IMG_0507.jpg",
  "IMG_0509.jpg",
  "IMG_0510.jpg",
  "IMG_0511.jpg",
  "IMG_0512.jpg",
  "IMG_0513.jpg",
  "IMG_0514.jpg",
  "IMG_0515.jpg",
  "IMG_0542.jpg",
  "IMG_0543.jpg",
  "IMG_0544.jpg",
  "IMG_0643.jpg",
  "IMG_0645.jpg",
  "IMG_0683.jpg",
  "IMG_0684.jpg",
  "IMG_0685.jpg",
  "IMG_0686.jpg",
  "IMG_0784.jpg",
  "IMG_0902.jpg",
  "IMG_0903.jpg",
  "IMG_0910.jpg",
  "IMG_0911.jpg",
  "IMG_0912.jpg",
  "IMG_0971.jpg",
  "IMG_0973.jpg",
  "IMG_0976.jpg",
  "IMG_1192.jpg",
  "IMG_1292.jpg",
  "IMG_1293.jpg",
  "IMG_1295.jpg",
  "IMG_1350.jpg",
  "IMG_1402.jpg",
  "IMG_1418.jpg",
  "IMG_1419.jpg",
  "IMG_1422.jpg",
  "IMG_1423.jpg",
  "IMG_1515.jpg",
  "IMG_1516.jpg",
  "IMG_1520.jpg",
  "IMG_1521.jpg",
  "IMG_2559.jpg",
  "IMG_2794.jpg",
  "IMG_2795.jpg",
  "IMG_3653.jpg",
  "IMG_3690.jpg",
  "IMG_4540.jpg",
  "IMG_4541.jpg",
  "IMG_7772.jpg",
  "IMG_7872.jpg",
  "IMG_7873.jpg",
  "IMG_7874.jpg",
  "IMG_7875.jpg",
  "IMG_7876.jpg",
  "IMG_8555.jpg",
  "IMG_8557.jpg",
  "IMG_8572.jpg",
  "IMG_8805.jpg",
  "IMG_9157.jpg",
  "IMG_9160.jpg",
  "IMG_9166.jpg",
  "IMG_9170.jpg",
  "IMG_9207.jpg",
  "IMG_9246.jpg",
  "IMG_9261.jpg",
  "IMG_9266.jpg",
  "IMG_9267.jpg",
  "IMG_9462.jpg",
  "IMG_9595.jpg",
  "IMG_9792.jpg",
  "IMG_9922.jpg",
  "IMG_9965.jpg",
  "IMG_9984.jpg",
  "z1.jpeg",
  "z2.jpeg",
  "z3.jpeg",
  "z4.jpeg",
  "z5.jpeg",
  "z6.jpeg"
];

const imgDescBHS = [
  "Project Adventure,Project Adventure Structure",
  "Achievement,Wrestling Room",
  "Gallery,Library Lobby",
  "Refusal,Lower Library",
  "Loading Bay,Health Hallway",
  "Janitors Office,Health Hallway",
  "Lioness,Art Hallway",
  "Sick Ride,Fieldhouse (Varsity Field)",
  "House Fire,Roundabout",
  "Nobody Here,Cafeteria",
  "Reading Time,Upper Library",
  "Wet Floor,Main Street",
  "Early Learning,Preschool",
  "Finally,Loading Bay (Health Hallway)",
  "The North Pole,Mrs. Giampapa's Room (Language Hallway)",
  "Wheelchair,Boys Locker Room",
  "Payphone Monument,Gym Lobby",
  "Welcome to Hell,Lower Library",
  "Forbidden Science,Science Hallway",
  "Forbidden Science 2,Science Hallway",
  "Mr. Leonard's Room,Science Hallway",
  "Authorized Personnel Only,Science Hallway",
  "Too Bad,Science Hallway",
  "Mrs. Cherwinski's Room,Science Hallway",
  "Greek City,Upper Library",
  "Greek City (Flash),Upper Library",
  "Ghost,Upper Library",
  "Run,Language Hallway",
  "Red Light,Science Hallway",
  "Red Light (Flash),Science Hallway",
  "Storage Closet,Main Lobby",
  "Monument,Lower Library",
  "Rising Sun,Varsity Field",
  "Finally 2,Fieldhouse (Varsity Field)",
  "Ghost Town,Former Project Adventure Course",
  "Rope Swing,Former Project Adventure Course",
  "Hamlet,Mrs. Crossman's Room (English Hallway)",
  "Death Spiral,Backstage",
  "Death Spiral 2,Backstage",
  "Stage-master,Backstage",
  "Don't Go Up,Backstage",
  "Grate,Backstage",
  "Senior Night,Varsity Field",
  "Paranormal,Auditorium Lobby",
  "Cloudy Day,Varsity Field",
  "Station Wagon,Faculty Parking Lot",
  "Worthless,Fitness Center Storage Room",
  "Clutter,Fitness Center Storage Room",
  "Battle,Fitness Center Storage Room",
  "Night of Fire,Lower Library",
  "Ride to the Sky,Varsity Field",
  "Escape,English Hallway",
  "Do Not Enter,History Hallway",
  "Mystery,Childhood Development Classroom",
  "Decline,Prop Room",
  "Track Meet,Press Box (Varsity Field)",
  "Track Meet 2,Press Box (Varsity Field)",
  "Storage Closet,English Hallway",
  "Rotary Phone, English Hallway",
// Barricade, Auditorium Lobby
// Vandals,Elevator Lobby (Gym Hallway)
// Workout,Fitness Center
// Under Construction,Lower Library
// Under Construction 2,Lower Library
// Gyatt,Varsity Field
  "Basement,Basement",
  "Basement 2,Basement",
  // "Basement 5,Basement",
  "Omen,Varsity Field",
  "Level,Boys Locker Room",
  "One Day,Elevator Lobby (Gym Hallway)",
  "Bad Weather,Elevator Lobby (Gym Hallway)",
  "Windows 95,Mac Lab (English Hallway)",
  "Winter Adventure,Project Adventure Structure",
  "Field Closed,Varsity Field",
  "Field Closed 2,Varsity Field",
  "Footprints,Varsity Field",
  "Lone Flag,Varsity Field",
  "Hazard,Auditorium",
  "Judgement,Auditorium",
  "Unknown,Practice Field",
  "Sculpture,Varsity Field",
  "Mr. Parkin's Room,History Hallway",
  "WD-40,Varsity Field",
  "Pimp My Ride,Varsity Field",
  "Emergency,Gym Parking Lot",
  "Graffiti,Gym Parking Lot",
  "Nobody Home,Auditorium",
  "Respect,Cafeteria Lobby",
  "Waxing,Wooden Gym",
  "Basketball,Rubber Gym",
  "Meeting,Teacher Lounge (Cafeteria)",
  "Go Devils,Boys Locker Room",
  "Magic,Gym Parking Lot",
  "Showers,Boys Locker Room",
  "Piano Man,Music Hallway",
  "Two Moons,Gym Parking Lot",
  "Poltergeist,Boys Locker Room",
  "Hawthorne Sucks,Mr. Pustizzi’s Room (English Hallway)",
  "Vandals,Elevator Lobby (Gym Hallway)",
  "Basement 3,Basement",
  "Basement 4,Basement",
  "Storage Closet 2, English Hallway",
];