const imgPrefixPG = "/building_photos_archive/pg/";
const imgListPG = [
  "IMG_0991.jpg",
  "IMG_0992.jpg",
  "IMG_0993.jpg",
  "IMG_0994.jpg",
  "IMG_0995.jpg",
  "IMG_0996.jpg", // portrait
  "IMG_0997.jpg",
  "IMG_0998.jpg",
  "IMG_0999.jpg",
  "IMG_1001.jpg",
  "IMG_1002.jpg",
  "IMG_1003.jpg",
  "IMG_1004.jpg",
  "IMG_1005.jpg",
  "IMG_1006.jpg",
  "IMG_1008.jpg",
  "IMG_1009.jpg",
  "IMG_1010.jpg",
  "IMG_1011.jpg",
  "IMG_1012.jpg",
  "IMG_2871.jpg",
  "IMG_2874.jpg",
  "IMG_2875.jpg",
  "IMG_9380.jpg",
  "IMG_9382.jpg",
  "IMG_9383.jpg",
  "IMG_9384.jpg"
];

const imgDescPG = [
  "Folded,Cafeteria",
  "Under the Sea,Stairwell",
  "Flowers,Classroom (Lower Hallway)",
  "Portrait,Lower Hallway",
  "Aqua,Elevator (Lower Hallway)",
  "Clutter,Art Room (Lower Hallway)",
  "Book Fair,Library",
  "Terabithia,Library",
  "Shrine,Outdoor Patio",
  "Mural,Main Lobby",
  "Popsicles,Cafeteria Line",
  "Buggy Hotel,Outdoor Benches",
  "Four-Square,Gym Wall",
  "The Wilderness,Tetherball Area",
  "Basketball,Basketball Court",
  "Mile,Gym Gate",
  "Secret Room,Playground",
  "Caterpillar Spaceship,Playground",
  "Contest,Playground",
  "Soccer,Side Field",
  "Goodbye,Side Field",
  "Kickball 1,Baseball Field",
  "Kickball 2,Baseball Field",
  "Welcome,Side Field",
  "Overgrown,Baseball Field",
  "Fences,Playground",
  "Cubbys,Lower Hallway"
];